apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab4-deployment
  labels:
    app: lab4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab4
  template:
    metadata:
      labels:
        app: lab4
    spec:
      containers:
      - name: lab4-container
        image: ifilyaninitmo/itdt-contained-frontend:master
        env:
        - name: REACT_APP_USERNAME
          value: my_USERNAME
        - name: REACT_APP_COMPANY_NAME
          value: my_COMPANY_NAME
        ports:
        - containerPort: 3000