apiVersion: v1
kind: Service
metadata:
  name: lab4-service
  labels:
    app: lab4
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 32000
    protocol: TCP
  selector:
    app: lab4