apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab2
  labels:
    app: lab2-react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab2-react
  template:
    metadata:
      labels:
        app: lab2-react
    spec:
      containers:
      - name: lab2-react
        image: ifilyaninitmo/itdt-contained-frontend:master
        env:
        - name: REACT_APP_USERNAME
          value: my_USERNAME
        - name: REACT_APP_COMPANY_NAME
          value: my_COMPANY_NAME
        ports:
        - containerPort: 3000