apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: lab3-replicaset
  labels:
    app: lab3-react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab3-react
  template:
    metadata:
      labels:
        app: lab3-react
    spec:
      containers:
      - name: lab3-container
        image: ifilyaninitmo/itdt-contained-frontend:master
        envFrom:
          - configMapRef:
              name: lab3-configmap
        ports:
        - containerPort: 3000